### ISSUE TITLE
Vertex: syntax error in gtk-contained.css gtk-contained-dark.css UnityDecoration

### ISSUE THREAD

**Issue by wolfland** [horst3180/Vertex-theme#129]
I found a syntax error in Vertex gtk-contained.css and gtk-contained-dark.css
in all three directories:

diff Downloads/Themes/Work/Vertex/gtk-3.0/gtk-contained.css 
     vs Theme/Work/Vertex/gtk-3.0/gtk-contained.css

< is before my changes
> is after my changes

4175c4175
<   -UnityDecoration-active-shadow-color: rgba 0, 0, 0, 0.75;
---
>   -UnityDecoration-active-shadow-color: rgba (0, 0, 0, 0.75);
4177c4177
<   -UnityDecoration-inactive-shadow-color: rgba 0, 0, 0, 0.3;
---
>   -UnityDecoration-inactive-shadow-color: rgba (0, 0, 0, 0.3);
4180c4180
<   -UnityDecoration-glow-color: rgb 64, 128, 251;
---
>   -UnityDecoration-glow-color: rgb (64, 128, 251);

This problem really threw me at first as I was making minor changes to my
unity.css addon to your code for both Arc and Vertex but was getting
differing results from the same code when used with Vertex(e.g. my unity 
code changes are very small and should perform the same on either theme).

The problem was that when I removed an unneeded duplicate line of code in
my file for the UnityDecoration-glow-color everything worked fine for Arc
but the UnityDecoration-glow-color for Vertex changed to the default Orange.

Evidently I had encountered this error before and just added the code to
correctly set the UnityDecoration-glow-color instead of trying to find out
why it wasn't working properly.

I took the time today to find the root cause of the problem instead of
just putting a band-aid on it.

The problem appears to be due to missing parenthesis around rgba statements
in the Vertex UnityDecoration code. Adding the parenthesis corrected the
problem and my addon code works correctly now for both Vertex and Arc.

Thanks,
WolfLand

**Comment by horst3180** [comment]
This is fixed with https://github.com/horst3180/Vertex-theme/commit/5380251fa8e81429c5c16bfa821a8e82609e5b04. Apparently Sass doesn't like it when you put a space before the braces.

**Comment by wolfland** [comment]
I think you missed UnityDecoration-glow-color as it appears to not have any parenthesis around
the rgb statement in the latest version(e.g. 5380251).

**Comment by horst3180** [comment]
Oh, yes I missed that one. Now it should be ok.

**Comment by wolfland** [comment]
Looks ok now. We used to use awk, sed and grep scripts to search for and
make changes like this(e.g. search for " (" and change to "(" and such).

I guess a css tidy or validator plugin or app probably wouldn't help 
since the
problem is with sass and not with the actual css syntax or formatting.

Oh well..

Thanks,
WolfLand
